name: awexpenses
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get:
  fl_chart: ^0.71.0
  hive:
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
